### PR TITLE
update nzb sources page

### PR DESCRIPTION
**Pull request by thezoggy**
Updated indexer list off reddit thread, removed financial related items (lots were out of date / we dont want to make it look like sab benefits or recommends anyone specifically), added disclaimers, use defer for links.

### CODE REVIEW

**Comment by Safihre** [comment]
Why all the `dereferer.org` links? Why block the indexers from knowing they came from our page?

**Comment by thezoggy** [comment]
reddit did that, so i just left them..

**Comment by Safihre** [comment]
Isn't it a bit weird to just be a copy of the Reddit page? I see it's really just the Reddit ones, even though we had some before that were not on the list..
Do you think our users are interested which type of platform it is? That doesn't matter for them at all when they use it or use it in combination with SAB.

**Comment by thezoggy** [comment]
its not a direct copy of the reddit page, i took what we had and merged it with theirs (monthly/yearly) and removed some columns..  the platform is a huge deal imho... theres so many indexers out there.. if people only use sites that have the same back end.. chances are they will only get the same nzb's...  for sab's purpose.. the backend is what dictates what format the category matches..  

keeping this page up to date is going to be a choir. maybe we should just drop all the info and just link to the reddit page?

**Comment by Safihre** [comment]
I was thinking that to, but analytics seem to show that this page is quite popular (compared to Config-help pages). 

For example of the last 3 weeks:
image

**Comment by thezoggy** [comment]
ok, so what would you like me to change then to get this pulled/closed out ?

**Comment by Safihre** [comment]
That makes it sound like for example every Newznab provider is the same, while that's not the case at all since the customizations each site did are what matter. OZnzb and PFMonkey definitly generate different results, despite both using Newznab.
So since it's the SABnzbd site, I would rather have the category specification (if known) that people would use in SABnzbd, than the software running the indexer. 
I saw some that are not on the new list anymore, like AlbumsIndex and usenet-crawler.com.

**Comment by thezoggy** [comment]
albums was removed, its more of a 'search engine' site that hadnt been updated in forever. usenet-crawler has been down for a bit

**Comment by thezoggy** [comment]
removed defer links and force pushed

**Comment by Safihre** [comment]
Will merge it in and then adapt it a tiny bit to the style of the rest of the wiki.
Thanks!

**Pull request merged**
